#!/bin/bash
clear
{
chk=$(cat /etc/ssh/sshd_config | grep Banner)
[[ $(netstat -nltp|grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
	[[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >>  /etc/default/dropbear
}
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
	local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}
echo -e "\E[44;1;37m                  MENSAJE DE BANNER               \E[0m"
echo ""
echo -e "\033[1;31m[\033[1;32m1\033[1;31m]\033[1;32m • \033[1;32mAGREGAR BANNER"
echo -e "\033[1;31m[\033[1;32m2\033[1;31m]\033[1;32m • \033[1;32mREMOVER BANNER"
echo -e "\033[1;31m[\033[1;32m0\033[1;31m]\033[1;32m • \033[1;32mVOLVER"
echo ""
echo -ne "\033[1;31mOPCION \033[1;31m?\033[1;32m: "; read resp
if [[ "$resp" = "1" ]]; then
echo ""
echo -ne "\033[1;32mMENSAJE A MOSTRAR: "; read msg1
if [[ -z "$msg1" ]]; then
	echo -e "\n\033[1;31mCampo vacio o invalido!\033[0m"
	sleep 2s
	banner
fi
echo -e "\n\033[1;31m[\033[1;32m01\033[1;31m]\033[1;32m FUENTE PEQUENA"
echo -e "\033[1;31m[\033[1;32m02\033[1;31m]\033[1;32m FUENTE MEDIA"
echo -e "\033[1;31m[\033[1;32m03\033[1;31m]\033[1;32m FUENTE GRANDE"
echo -e "\033[1;31m[\033[1;32m04\033[1;31m]\033[1;32m FUENTE GIGANTE"
echo ""
echo -ne "\033[1;32mTAMAÑO DE FUENTE: "; read opc
if [[ "$opc" = "1" ]] || [[ "$opc" = "01" ]]; then
_size='6'
elif [[ "$opc" = "2" ]] || [[ "$opc" = "02" ]]; then
_size='4'
elif [[ "$opc" = "3" ]] || [[ "$opc" = "03" ]]; then
_size='3'
elif [[ "$opc" = "4" ]] || [[ "$opc" = "04" ]]; then
_size='1'
fi

echo -e "\n\033[1;31m[\033[1;32m01\033[1;31m]\033[1;32m AZUL"
echo -e "\033[1;31m[\033[1;32m02\033[1;31m]\033[1;32m VERDE"
echo -e "\033[1;31m[\033[1;32m03\033[1;31m]\033[1;32m ROJO"
echo -e "\033[1;31m[\033[1;32m04\033[1;31m]\033[1;32m AMARILLO"
echo -e "\033[1;31m[\033[1;32m05\033[1;31m]\033[1;32m ROSA"
echo -e "\033[1;31m[\033[1;32m06\033[1;31m]\033[1;32m CYAN"
echo -e "\033[1;31m[\033[1;32m07\033[1;31m]\033[1;32m NARANJA"
echo -e "\033[1;31m[\033[1;32m08\033[1;31m]\033[1;32m PURPURA"
echo -e "\033[1;31m[\033[1;32m09\033[1;31m]\033[1;32m NEGRO"
echo -e "\033[1;31m[\033[1;32m10\033[1;31m]\033[1;32m SIN COLOR"
echo ""
echo -ne "\033[1;32mCOLOR: "; read ban_cor
if [[ "$ban_cor" = "1" ]] || [[ "$ban_cor" = "01" ]]; then
echo "<h$_size><font color='blue'>$msg1" >> $local
elif [[ "$ban_cor" = "2" ]] || [[ "$ban_cor" = "02" ]]; then
echo "<h$_size><font color='green'>$msg1" >> $local
elif [[ "$ban_cor" = "3" ]] || [[ "$ban_cor" = "03" ]]; then
echo "<h$_size><font color='red'>$msg1" >> $local
elif [[ "$ban_cor" = "4" ]] || [[ "$ban_cor" = "04" ]]; then
echo "<h$_size><font color='yellow'>$msg1" >> $local
elif [[ "$ban_cor" = "5" ]] || [[ "$ban_cor" = "05" ]]; then
echo "<h$_size><font color='#F535AA'>$msg1" >> $local
elif [[ "$ban_cor" = "6" ]] || [[ "$ban_cor" = "06" ]]; then
echo "<h$_size><font color='cyan'>$msg1" >> $local
elif [[ "$ban_cor" = "7" ]] || [[ "$ban_cor" = "07" ]]; then
echo "<h$_size><font color='#FF7F00'>$msg1" >> $local
elif [[ "$ban_cor" = "8" ]] || [[ "$ban_cor" = "08" ]]; then
echo "<h$_size><font color='#9932CD'>$msg1" >> $local
elif [[ "$ban_cor" = "9" ]] || [[ "$ban_cor" = "09" ]]; then
echo "<h$_size><font color='black'>$msg1" >> $local
elif [[ "$ban_cor" = "10" ]]; then
echo "<h$_size>$msg1</h$_size>" >> $local
/etc/init.d/ssh restart > /dev/null 2>&1
echo -e "\n\033[1;32mBANNER AGREGADO!\033[0m"
sleep 2s
menu
else
echo -e "\n\033[1;31mOpcion invalida!\033[0m"
	sleep 2s
	banner
fi
echo "</font></h$_size>" >> $local
service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
echo -e "\n\033[1;32mBANNER AGREGADO!\033[0m"
unset ban_cor
elif [[ "$resp" = "2" ]]; then
	echo " " > $local
	echo -e "\n\033[1;32mBANNER EXCLUIDO!\033[0m"
	service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
	sleep 2s
	menu
elif [[ "$resp" = "0" ]]; then
	menu
else
	echo -e "\n\033[1;31mOpcion invalida!\033[0m"
	sleep 2s
	banner
fi
}