#!/bin/bash           
users_database="/root/usuarios.db"   
block_userfun () {
local USRloked="/etc/VPNPro/blockuser"
if [[ $(cat ${USRloked}|grep -w "$1") ]]; then
usermod -U "$1" &>/dev/null
[[ -e ${USRloked} ]] && {
newbase=$(cat ${USRloked}|grep -w -v "$1")
[[ -e ${USRloked} ]] && rm ${USRloked}
for value in `echo ${newbase}`; do
echo $value >> ${USRloked}
done
}
return 1
else
usermod -L "$1" &>/dev/null
echo $1 >> ${USRloked}
fi
}
block_user () {	
local USRloked="/etc/VPNPro/blockuser"
[[ ! -e ${USRloked} ]] && touch ${USRloked}
clear
echo -e "\E[44;1;37m                 BLOQUEO DE USUARIOS              \E[0m"
echo ""
for users in `awk  -F : '$3>=1000 {print  $1}'  /etc/passwd | grep -v "nobody" | sort`; do
i=$(expr $i + 1)
oP+=$i
[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
oP+=":$users\n"
if [[ $(cat ${USRloked}|grep -w "${users}") ]]; then
users=$(printf '%-15s' "${users}")
echo -ne "\033[01;31m[\033[01;32m$i\033[01;31m]\033[1;32m -" && echo -e "\033[1;32m ${users} \033[1;31mBLOQUEADO"
else
users=$(printf '%-15s' "${users}")
echo -ne "\033[01;31m[\033[01;32m$i\033[01;31m]\033[1;32m -" && echo -e "\033[1;32m ${users} \033[1;32mDESBLOQUEADO"
fi
done 
num=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
echo -e
echo -ne "\033[1;32mSeleccionar un usuario \033[1;31m1\033[1;31m-\033[1;31m$num\033[1;32m: " ; read number
if [[ -z $number ]]; then
echo ""
echo -e "\033[1;31mDebes seleccionar un usuario Inténtalo de nuevo!\033[0m"
exit 1
else
if [ "$number" = "0" ]; then
exit 1
else
user=$(echo -e "$oP" | grep -E "\b$number\b" | cut -d: -f2)
if [[ -z $user ]]; then
	echo ""
echo -e "\033[1;31mEl usuario no existe en la lista de usuarios!\033[0m"
exit 1
else
echo""
echo -ne "\033[1;32mUsuario: " && echo -ne "\033[1;31m$user "
block_userfun "$user" && echo -e "\033[1;31m [\033[1;31m BLOQUEADO\033[1;31m ]" || echo -e "\033[1;31m [\033[1;32m DESBLOQUEADO\033[1;31m ]"
pkill -f $user 1> /dev/null 2> /dev/null
sleep 2s
echo "" 
exit 1
fi
fi
fi

}

block_user