#!/bin/bash
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#	SCRIPT: CRIARUSUARIO VpnPlus
#	DESARROLLADO POR:	Diego Pinto
#	CONTACTO TELEGRAM:	https://t.me/DiegoPintoTM
#	CANAL TELEGRAM:	https://t.me/DiegoPintoTM
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IP=$(cat /etc/IP)
cor1='\033[44;1;37m'
cor2='\033[44;1;32m'
scor='\033[0m'
# Gerar client.ovpn
newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}
fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1
[[ -e /etc/openvpn/server.conf ]] && {
    _Port=$(grep -w 'port' /etc/openvpn/server.conf | awk {'print $2'})
    hst=$(sed -n '8 p' /etc/openvpn/client-common.txt | awk {'print $4'})
    rmt=$(sed -n '7 p' /etc/openvpn/client-common.txt)
    hedr=$(sed -n '8 p' /etc/openvpn/client-common.txt)
    prxy=$(sed -n '9 p' /etc/openvpn/client-common.txt)
    rmt2='/VPNPRO?'
    rmt3='www.movistar.com.co 8088'
    prx='200.142.130.104'
    payload1='#payload "HTTP/1.0 [crlf]Host: c.whatsapp.net[crlf]CONNECT HTTP/1.0[crlf][crlf]|[crlf]"'
    payload2='#payload "CONNECT 127.0.0.1:1194[split][crlf] HTTP/1.0 [crlf][crlf]#"'
    movistar1="multimedia.epayco.co/recarga"
    movistar2="multimedia.epayco.co/controle/"
    movistar3="navegue.movistar.com.co/pre/"
    movistar4="navegue.movistar.com.co/controle/"
    movistar5="www.movistar.com.co"
    oi="d1n212ccp6ldpw.cloudfront.net"
    bypass="net_gateway"
    cert01="/etc/openvpn/client-common.txt"
    if [[ "$hst" == "$movistar1" ]]; then
        Host="Portal Recarga"
    elif [[ "$hst" == "$movistar2" ]]; then
        Host="Recarga contole"
    elif [[ "$hst" == "$movistar3" ]]; then
        Host="Portal Navegue"
    elif [[ "$hst" == "$movistar4" ]]; then
        Host="Nav controle"
    elif [[ "$hst" == "$IP:$_Port" ]]; then
        Host="Vivo MMS"
    elif [[ "$hst" == "$oi" ]]; then
        Host="Oi"
    elif [[ "$hst" == "$bypass" ]]; then
        Host="Modo Bypass"
    elif [[ "$hedr" == "$payload1" ]]; then
        Host="OPEN SOCKS"
    elif [[ "$hedr" == "$payload2" ]]; then
        Host="OPEN SQUID"
    else
        Host="Customizado"
    fi
}
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} >/dev/null 2>&1
        ${comando[1]} >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;32mAGUARDE \033[1;32m- \033[1;32m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;32m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;32mAGUARDE \033[1;32m- \033[1;32m["
    done
    echo -e "\033[1;32m]\033[1;32m -\033[1;31m OK!\033[1;32m"
    tput cnorm
}
fun_edithost() {
    clear
    echo -e "\E[44;1;37m                 CAMBIAR HOST OVPN                \E[0m"
    echo ""
    echo -e "\033[1;32mHOST EN USO\033[1;32m: \033[1;31m$Host"
    echo ""
    echo -e "\033[1;32m[\033[1;32m1\033[1;32m] \033[1;32mVIVO RECARGA"
    echo -e "\033[1;32m[\033[1;32m2\033[1;32m] \033[1;32mVIVO NAVEGUE PRE"
    echo -e "\033[1;32m[\033[1;32m3\033[1;32m] \033[1;32mOPEN SOCKS \033[1;32m[\033[1;32mAPP MOD\033[1;32m]"
    echo -e "\033[1;32m[\033[1;32m4\033[1;32m] \033[1;32mOPEN SQUID \033[1;32m[\033[1;32mAPP MOD\033[1;32m]"
    echo -e "\033[1;32m[\033[1;32m5\033[1;32m] \033[1;32mVIVO MMS \033[1;32m[\033[1;32mAPN: \033[1;32mmms.movistar.com.co\033[1;32m]"
    echo -e "\033[1;32m[\033[1;32m6\033[1;32m] \033[1;32mMODO BYPASS \033[1;32m[\033[1;32mOPEN + INJECTOR\033[1;32m]"
    echo -e "\033[1;32m[\033[1;32m7\033[1;32m] \033[1;32mTODOS HOSTS \033[1;32m[\033[1;32m1 OVPN DE CADA\033[1;32m]"
    echo -e "\033[1;32m[\033[1;32m8\033[1;32m] \033[1;32mEDITAR MANUALMENTE"
    echo -e "\033[1;32m[\033[1;32m0\033[1;32m] \033[1;32mVOLVER"
    echo ""
    echo -ne "\033[1;32mCUAL HOST DESEA USAR: "
    read respo
    [[ -z "$respo" ]] && {
        echo -e "\n\033[1;32mOpcion invalida!"
        sleep 2s
        fun_edithost
    }
    if [[ "$respo" = '1' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althost() {
            sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $movistar1;" $cert01
            sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althost'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '2' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althost2() {
            sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $movistar3;" $cert01
            sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althost2'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '3' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althostpay1() {
            sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sed -i "s;$hedr;$payload1;" $cert01
            sed -i "s;$prxy;http-proxy $IP 8080;" $cert01
        }
        fun_bar 'fun_althostpay1'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '4' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althostpay2() {
            sed -i "s;$rmt;remote $rmt2 $_Port;" $cert01
            sed -i "s;$hedr;$payload2;" $cert01
            sed -i "s;$prxy;http-proxy $IP 80;" $cert01
        }
        fun_bar 'fun_althostpay2'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '5' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althost5() {
            sed -i "s;$rmt;remote $rmt3;" $cert01
            sed -i "s;$hedr;http-proxy-option CUSTOM-HEADER Host $IP:$_Port;" $cert01
            sed -i "s;$prxy;http-proxy $prx 80;" $cert01
        }
        fun_bar 'fun_althost5'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '6' ]]; then
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_althost6() {
            sed -i "s;$rmt;remote $IP $_Port;" $cert01
            sed -i "s;$hedr;route $IP 255.255.255.255 net_gateway;" $cert01
            sed -i "s;$prxy;http-proxy 127.0.0.1 8989;" $cert01
        }
        fun_bar 'fun_althost6'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '7' ]]; then
        [[ ! -e "$HOME/$username.ovpn" ]] && fun_geraovpn
        echo -e "\n\033[1;32mCAMBIANDO HOST!\033[0m\n"
        fun_packhost() {
            [[ ! -d "$HOME/OVPN" ]] && mkdir $HOME/OVPN
            sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5s
            sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $movistar1\nhttp-proxy $IP 80" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-movistar1.ovpn
            sed -i "8"d $HOME/$username.ovpn
            sleep 0.5s
            sed -i "8i\http-proxy-option CUSTOM-HEADER Host $movistar3" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-movistar2.ovpn
            sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5s
            sed -i "7i\remote $rmt3\nhttp-proxy-option CUSTOM-HEADER Host $IP:$_Port\nhttp-proxy $prx 80" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-movistar3.ovpn
            sed -i "7,9"d $HOME/$username.ovpn
            sleep 0.5s
            sed -i "7i\remote $IP $_Port\nroute $IP 255.255.255.255 net_gateway\nhttp-proxy 127.0.0.1 8989" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-bypass.ovpn
			sed -i "7,9"d $HOME/$username.ovpn
			sleep 0.5s
			sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-socks.ovpn
			sed -i "7,9"d $HOME/$username.ovpn
			sleep 0.5s
			sed -i "7i\remote $rmt2 $_Port\n$payload2\nhttp-proxy $IP 80" $HOME/$username.ovpn
            cp $HOME/$username.ovpn /root/OVPN/$username-squid.ovpn
            cd $HOME/OVPN && zip $username.zip *.ovpn >/dev/null 2>&1 && cp $username.zip $HOME/$username.zip
            cd $HOME && rm -rf /root/OVPN >/dev/null 2>&1
        }
        fun_bar 'fun_packhost'
        echo -e "\n\033[1;32mHOST CAMBIADO CON EXITO!\033[0m"
        sleep 1.5s
    elif [[ "$respo" = '8' ]]; then
        echo ""
        echo -e "\033[1;32mCAMBIANDO ARCHIVO OVPN!\033[0m"
        echo ""
        echo -e "\033[1;32mATENCION!\033[0m"
        echo ""
        echo -e "\033[1;32mPARA GUARDAR USE LAS TECLAS \033[1;32mctrl x y\033[0m"
        sleep 4s
        clear
        nano /etc/openvpn/client-common.txt
        echo ""
        echo -e "\033[1;32mCAMBIADO CON EXITO!\033[0m"
        fun_geraovpn
        sleep 1.5s
    elif [[ "$respo" = '0' ]]; then
        echo ""
        echo -e "\033[1;32mVOLVIENDO...\033[0m"
        sleep 2s
    else
        echo ""
        echo -e "\033[1;32mOpcion Invalida!\033[0m"
        sleep 2s
        fun_edithost
    fi
}
[[ ! -e /usr/lib/vpnpro ]] && exit 0
tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "                 CREAR USUARIO SSH ";tput sgr0
echo ""
echo -ne "\033[1;31mNombre de usuario:\033[1;32m ";read username
[[ -z $username ]] && {
	echo -e "\n${cor1}Nombre de usuario vacio o invalido!${scor}\n"
	exit 1
}
[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
	echo -e "\n${cor1}El usuario ya existe. intente otro nombre!${scor}\n"
	exit 1
}
[[ ${username} != ?(+|-)+([a-zA-Z0-9-/]) ]] && {
	echo -e "\n${cor1}Ingreso un nombre de usuario inválido!${scor}"
	echo -e "${cor1}No use espacios,o caracteres especiales!${scor}\n"
	exit 1
}
sizemin=$(echo ${#username})
[[ $sizemin -lt 2 ]] && {
	echo -e "\n${cor1}Ingreso un nombre de usuario muy corto${scor}"
	echo -e "${cor1}use minimo dos caracteres!${scor}\n"
	exit 1
}
sizemax=$(echo ${#username})
[[ $sizemax -gt 12 ]] && {
	echo -e "\n${cor1}Ingreso un nombre de usuario muy grande"
	echo -e "${cor1}use máximo 12 caracteres!${scor}\n"
	exit 1
}
echo -ne "\033[1;31mContraseña:\033[1;32m ";read password
[[ -z $password ]] && {
	echo -e "\n${cor1}Contraseña vacia o invalida!${scor}\n"
	exit 1
}
sizepass=$(echo ${#password})
[[ $sizepass -lt 4 ]] && {
	echo -e "\n${cor1}Contraseña corta!, usa al menos 4 caracteres${scor}\n"
	exit 1
}
echo -ne "\033[1;31mDias para expirar:\033[1;32m ";read dias
[[ -z $dias ]] && {
	echo -e "\n${cor1}Numero de dias vacio!${scor}\n"
	exit 1
}
[[ ${dias} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}Ingreso un numero de dias invalido!${scor}\n"
	exit 1
}
[[ $dias -lt 1 ]] && {
	echo -e "\n${cor1}El numero debe ser mayor a cero!${scor}\n"
	exit 1
}
echo -ne "\033[1;31mLimite de conexiones:\033[1;32m ";read sshlimiter
[[ -z $sshlimiter ]] && {
	echo -e "\n${cor1}Dejaste el limite de conexiones vacio!${scor}\n"
	exit 1
}
[[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}ingreso un numero de conexiones invalido!${scor}\n"
	exit 1
}
[[ $sshlimiter -lt 1 ]] && {
	echo -e "\n${cor1}Numero de conexiones debe ser mayor a cero!${scor}\n"
	exit 1
}
final=$(date "+%Y-%m-%d" -d "+$dias days")
gui=$(date "+%d/%m/%Y" -d "+$dias days")
pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
echo "$password" >/etc/VPNPro/senha/$username
echo "$username $sshlimiter" >>/root/usuarios.db
[[ -e /etc/openvpn/server.conf ]] && {
	echo -ne "\033[1;32mCrear Archivo Ovpn [s/n]: "; read resp
	[[ "$resp" = @(s|S) ]] && {
		rm $username.zip $username.ovpn >/dev/null 2>&1
		echo -ne "\033[1;32mCrear con usuario y contraseña [s/n]: \033[1;32 "
		read respost
		echo -ne "\033[1;32mHost Actual\033[1;32m: \033[1;32m(\033[1;31m$Host\033[1;32m) \033[1;32m- \033[1;32mCambiar [s/n] : \033[1;32 "; read oprc
		[[ "$oprc" = @(s|S) ]] && {
			fun_edithost
		} || {
			fun_geraovpn
		}
		gerarovpn() {
			[[ ! -e "/root/$username.zip" ]] && {
				zip /root/$username.zip /root/$username.ovpn
				sleep 1.5s
			}
		}
		clear
		echo -e "\E[44;1;37mCUENTA SSH CREADA!\E[0m"
		echo -e "\n\033[1;31mIP: \033[1;32m$IP"
		echo -e "\033[1;31mUsuario: \033[1;32m$username"
		echo -e "\033[1;31mContraseña: \033[1;32m$password"
		echo -e "\033[1;31mCaduca en: \033[1;32m$gui"
		echo -e "\033[1;31mLimite de conexiones: \033[1;32m$sshlimiter"
		sleep 1s
		function aguarde() {
			helice() {
				gerarovpn >/dev/null 2>&1 &
				tput civis
				while [ -d /proc/$! ]; do
					for i in / - \\ \|; do
						sleep .1s
						echo -ne "\e[1D$i"
					done
				done
				tput cnorm
			}
			echo ""
			echo -ne "\033[1;32mCREANDO OVPN\033[1;32m.\033[1;32m.\033[1;31m \033[1;31m"
			helice
			echo -e "\e[1DOK"
		}
		aguarde
		VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
		echo ""
		[[ -d /var/www/html/openvpn ]] && {
			mv $HOME/$username.zip /var/www/html/openvpn/$username.zip >/dev/null 2>&1
			[[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]] && {
				echo -e "\033[1;32mLINK\033[1;32m: \033[1;31m$IP:81/html/openvpn/$username.zip"
			} || {
				echo -e "\033[1;32mLINK\033[1;32m: \033[1;31m$IP:81/openvpn/$username.zip"
			}
		} || {
			echo -e "\033[1;32mDisponible en\033[1;32m" ~/"$username.zip\033[0m"
			sleep 1s
		}
	} || {
		clear
		echo -e "\E[44;1;37mUSUARIO SSH CREADO CON EXITO!\E[0m"
		echo -e "\n\033[1;31mIP: \033[1;32m$IP"
		echo -e "\033[1;31mUsuario: \033[1;32m$username"
		echo -e "\033[1;31mContraseña: \033[1;32m$password"
		echo -e "\033[1;31mCaduca en: \033[1;32m$gui"
		echo -e "\033[1;31mLimite de conexiones: \033[1;32m$sshlimiter"
	}
} || {
	clear
	echo -e "\E[44;1;37mUSUARIO SSH CREADO CON EXITO!\E[0m"
	echo -e "\n\033[1;31mIP: \033[1;32m$IP"
	echo -e "\033[1;31mUsuario: \033[1;32m$username"
	echo -e "\033[1;31mContraseña: \033[1;32m$password"
	echo -e "\033[1;31mCaduca en: \033[1;32m$gui"
	echo -e "\033[1;31mLimite de conexiones: \033[1;32m$sshlimiter"
}
