#!/bin/bash
clear
{
echo -e "\033[1;31mATENCION!\033[0m"
echo " "
echo -e "\033[1;32mLA CONTRASEÑA SERA USADA PARA ENTRAR AL SERVIDOR!
\033[0m"
echo -e "\033[1;31mESCRIBA LA NUEVA CONTRASEÑA...\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mCONTRASEÑA CAMBIADA CON EXITO!\033[0m"
sleep 5s
cd
clear
}